class PresetManager {
    constructor(sceneManager, modelManager, envManager) {
        this.sceneManager = sceneManager;
        this.modelManager = modelManager;
        this.envManager = envManager;

        // Direction vectors (from model center) + up vectors, mirrors the
        // 12-angle turntable layout used by the reference ArrayCamera example.
        // Array order also defines the 4x3 grid slot (row-major) in the live preview.
        this.presets = [
            { name: 'Front',       dir: [0, 0, 1],       up: [0, 1, 0] },
            { name: 'Front Right', dir: [0.7, 0, 0.7],   up: [0, 1, 0] },
            { name: 'Right',       dir: [1, 0, 0],       up: [0, 1, 0] },
            { name: 'Back Right',  dir: [0.7, 0, -0.7],  up: [0, 1, 0] },
            { name: 'Back',        dir: [0, 0, -1],      up: [0, 1, 0] },
            { name: 'Back Left',   dir: [-0.7, 0, -0.7], up: [0, 1, 0] },
            { name: 'Left',        dir: [-1, 0, 0],      up: [0, 1, 0] },
            { name: 'Front Left',  dir: [-0.7, 0, 0.7],  up: [0, 1, 0] },
            { name: 'Top Front',   dir: [0, 0.8, 0.6],   up: [0, 0, -1] },
            { name: 'Top Right',   dir: [0.6, 0.8, 0],   up: [0, 0, -1] },
            { name: 'Top Back',    dir: [0, 0.8, -0.6],  up: [0, 0, 1] },
            { name: 'Top Left',    dir: [-0.6, 0.8, 0],  up: [0, 0, -1] }
        ];
        this.previewCols = 4;

        // Live multi-viewport preview (all angles at once), built lazily on first tab visit.
        this.previewRenderer = null;
        this.previewCanvas = null;
        this.arrayCamera = null;
        this.previewResizeObserver = null;
        this.previewActive = false;

        // Dedicated offscreen renderer used for per-angle downloads, so downloads
        // never disturb the main interactive camera or the live preview.
        this.offscreenRenderer = null;
        this.offscreenCanvas = null;

        // Each extra renderer above has its own WebGL context, so it can't reuse the
        // PMREM environment texture generated by the main renderer (that texture only
        // lives in the main context's GPU memory). Each gets its own PMREM copy here.
        this.envCache = {};
    }

    // Bounding sphere of the currently loaded model, in world space.
    getModelSphere() {
        const THREE = ThreeBundle.THREE;
        const model = this.modelManager.model;
        if (!model) {
            return { center: new THREE.Vector3(0, 0, 0), radius: 3 };
        }
        const box = new THREE.Box3().setFromObject(model);
        const sphere = new THREE.Sphere();
        box.getBoundingSphere(sphere);
        return { center: sphere.center, radius: sphere.radius || 3 };
    }

    // Camera distance that keeps the model's bounding sphere inside the given FOV.
    computePosition(dirArr, fov) {
        const THREE = ThreeBundle.THREE;
        const { center, radius } = this.getModelSphere();
        const distance = (radius / Math.sin(THREE.MathUtils.degToRad(fov / 2))) * 1.35;
        const dir = new THREE.Vector3(...dirArr).normalize();
        const position = center.clone().addScaledVector(dir, distance);
        return { position, center };
    }

    applyPreset(preset) {
        const fov = this.sceneManager.camera.fov || 45;
        const { position, center } = this.computePosition(preset.dir, fov);
        const camera = this.sceneManager.camera;

        camera.up.set(...preset.up);
        camera.position.copy(position);
        camera.lookAt(center);

        if (this.sceneManager.controls) {
            this.sceneManager.controls.target.copy(center);
            this.sceneManager.controls.update();
        }
        camera.updateProjectionMatrix();
        this.sceneManager.render();
    }

    // A sensible default up-vector for a given look direction: horizontal up for
    // eye-level angles, and a flat up for near-vertical (top/bottom-down) angles.
    computeUpForDir(dir) {
        const [, y] = dir;
        if (Math.abs(y) > 0.9) {
            return [0, 0, y > 0 ? -1 : 1];
        }
        return [0, 1, 0];
    }

    addPreset(name, dir) {
        const preset = {
            name: name || `Angle ${this.presets.length + 1}`,
            dir: dir || [0, 0, 1],
            up: this.computeUpForDir(dir || [0, 0, 1])
        };
        this.presets.push(preset);
        this.rebuildPreviewCameras();
        return preset;
    }

    removePreset(index) {
        this.presets.splice(index, 1);
        this.rebuildPreviewCameras();
    }

    // Call after directly mutating a preset's dir so its up-vector and the live preview stay in sync.
    updatePresetDir(index) {
        const preset = this.presets[index];
        if (!preset) return;
        preset.up = this.computeUpForDir(preset.dir);
        this.rebuildPreviewCameras();
    }

    // ── Live "all angles at once" preview ───────────────────────────────────

    initPreview(canvas) {
        const THREE = ThreeBundle.THREE;
        this.previewCanvas = canvas;
        this.previewRenderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true });
        this.previewRenderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2));
        this.previewRenderer.outputColorSpace = THREE.SRGBColorSpace;
        this.previewRenderer.toneMapping = THREE.ACESFilmicToneMapping;
        this.previewRenderer.toneMappingExposure = this.sceneManager.renderer.toneMappingExposure;
        this.rebuildPreviewCameras();
    }

    // Rebuilds the ArrayCamera viewports/positions. Call on tab activate, resize, model load, or preset edits.
    rebuildPreviewCameras() {
        const THREE = ThreeBundle.THREE;
        if (!this.previewCanvas || !this.previewRenderer) return;

        const cssW = this.previewCanvas.clientWidth || 320;
        const cssH = this.previewCanvas.clientHeight || 240;
        if (cssW === 0 || cssH === 0) return;

        this.previewRenderer.setSize(cssW, cssH, false);
        const dpr = this.previewRenderer.getPixelRatio();
        const W = cssW * dpr;
        const H = cssH * dpr;
        const cols = this.previewCols;
        const rows = Math.max(1, Math.ceil(this.presets.length / cols));
        const cellW = W / cols;
        const cellH = H / rows;
        const fov = 45;

        this.previewCameras = this.presets.map((preset, i) => {
            const { position, center } = this.computePosition(preset.dir, fov);
            const col = i % cols;
            const row = Math.floor(i / cols);

            const cam = new THREE.PerspectiveCamera(fov, cellW / cellH, 0.01, 10000);
            cam.up.set(...preset.up);
            cam.position.copy(position);
            cam.lookAt(center);
            // Viewport y is measured from the bottom of the drawing buffer in physical pixels.
            cam.viewport = new THREE.Vector4(
                Math.floor(col * cellW),
                Math.floor(H - (row + 1) * cellH),
                Math.ceil(cellW),
                Math.ceil(cellH)
            );
            cam.updateMatrixWorld();
            return cam;
        });

        this.arrayCamera = new THREE.ArrayCamera(this.previewCameras);
    }

    // Called from the main render loop; only does work while the Presets tab is visible.
    renderPreview() {
        if (!this.previewActive || !this.previewRenderer || !this.arrayCamera) return;
        const scene = this.sceneManager.scene;
        const originalEnv = scene.environment;
        this.applyOwnEnvironment(this.previewRenderer, 'preview', scene);
        this.previewRenderer.render(scene, this.arrayCamera);
        scene.environment = originalEnv;
    }

    activatePreview(canvas) {
        if (!this.previewRenderer) {
            this.initPreview(canvas);
            this.previewResizeObserver = new ResizeObserver(() => this.rebuildPreviewCameras());
            this.previewResizeObserver.observe(canvas);
        } else {
            this.rebuildPreviewCameras();
        }
        this.previewActive = true;
    }

    deactivatePreview() {
        this.previewActive = false;
    }

    // ── Downloads (offscreen, never disturbs the main camera or the live preview) ──

    // Regenerates a PMREM environment map for the given renderer's own WebGL context.
    // A PMREM texture only lives in the GPU memory of the context that rendered it, so
    // it can't be reused as-is by a different WebGLRenderer/canvas — each needs its own.
    applyOwnEnvironment(renderer, cacheKey, scene) {
        const hdriTexture = this.envManager?.currentHDRITexture;
        if (!hdriTexture) return;

        const THREE = ThreeBundle.THREE;
        const state = this.envCache[cacheKey] || (this.envCache[cacheKey] = {});

        if (state.sourceTexture !== hdriTexture) {
            if (!state.pmremGenerator) {
                state.pmremGenerator = new THREE.PMREMGenerator(renderer);
                state.pmremGenerator.compileEquirectangularShader();
            }
            if (state.renderTarget) state.renderTarget.dispose();
            state.renderTarget = state.pmremGenerator.fromEquirectangular(hdriTexture);
            state.sourceTexture = hdriTexture;
        }

        scene.environment = state.renderTarget.texture;
    }

    getOffscreenRenderer() {
        const THREE = ThreeBundle.THREE;
        if (!this.offscreenRenderer) {
            this.offscreenCanvas = document.createElement('canvas');
            this.offscreenRenderer = new THREE.WebGLRenderer({ canvas: this.offscreenCanvas, antialias: true, alpha: true });
            this.offscreenRenderer.outputColorSpace = THREE.SRGBColorSpace;
            this.offscreenRenderer.toneMapping = THREE.ACESFilmicToneMapping;
            this.offscreenRenderer.toneMappingExposure = this.sceneManager.renderer.toneMappingExposure;
        }
        return this.offscreenRenderer;
    }

    captureAngleBlob(preset, mimeType, width = 300, height = 300) {
        const THREE = ThreeBundle.THREE;
        return new Promise((resolve) => {
            const renderer = this.getOffscreenRenderer();
            const scene = this.sceneManager.scene;
            const fov = 45;
            const { position, center } = this.computePosition(preset.dir, fov);

            const camera = new THREE.PerspectiveCamera(fov, width / height, 0.01, 10000);
            camera.up.set(...preset.up);
            camera.position.copy(position);
            camera.lookAt(center);
            camera.updateMatrixWorld();

            const originalEnv = scene.environment;
            this.applyOwnEnvironment(renderer, 'offscreen', scene);
            renderer.setSize(width, height, false);
            renderer.render(scene, camera);
            scene.environment = originalEnv;
            this.offscreenCanvas.toBlob((blob) => resolve(blob), mimeType);
        });
    }

    triggerDownload(blob, name) {
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = name;
        link.click();
        URL.revokeObjectURL(url);
    }

    async downloadSingleAngle(preset, mimeType = 'image/webp', extension = 'webp', width = 300, height = 300) {
        const fileName = this.modelManager.getCurrentFileName();
        const blob = await this.captureAngleBlob(preset, mimeType, width, height);
        this.triggerDownload(blob, `${fileName}-${preset.name.replace(/\s+/g, '-').toLowerCase()}.${extension}`);
    }

    // Downloads every preset angle as a separate file. Sequential with a short
    // delay between saves so browsers don't block rapid multi-file downloads.
    async downloadAllAngles(mimeType = 'image/webp', extension = 'webp', width = 300, height = 300) {
        const fileName = this.modelManager.getCurrentFileName();

        for (const preset of this.presets) {
            const blob = await this.captureAngleBlob(preset, mimeType, width, height);
            this.triggerDownload(blob, `${fileName}-${preset.name.replace(/\s+/g, '-').toLowerCase()}.${extension}`);
            await new Promise((resolve) => setTimeout(resolve, 400));
        }
    }
}

window.PresetManager = PresetManager;
